"""empty message

Revision ID: 01c777670026
Revises: dc3b7ffa7151
Create Date: 2021-04-12 20:50:17.082302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c777670026'
down_revision = 'dc3b7ffa7151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('b_type', sa.String(length=80), nullable=False))
    op.drop_column('bike', 'bike_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('bike_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('bike', 'b_type')
    # ### end Alembic commands ###
