"""empty message

Revision ID: 34fe51184d56
Revises: fe1e351af93e
Create Date: 2021-04-19 16:50:20.303902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fe51184d56'
down_revision = 'fe1e351af93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('gears', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'gears')
    # ### end Alembic commands ###
