"""empty message

Revision ID: 3ef2c172b441
Revises: 01c777670026
Create Date: 2021-04-12 21:04:36.793006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef2c172b441'
down_revision = '01c777670026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('name', sa.String(length=80), nullable=True))
    op.drop_column('bike', 'bike_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('bike_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('bike', 'name')
    # ### end Alembic commands ###
