"""empty message

Revision ID: 475bd2a00e26
Revises: ef7e081822fd
Create Date: 2021-04-07 10:06:50.670584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475bd2a00e26'
down_revision = 'ef7e081822fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address1',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'address2',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'favorite_activities',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'postal_code',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'surname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'postal_code',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'favorite_activities',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'address2',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('user', 'address1',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
