"""empty message

Revision ID: 67c7c2181887
Revises: 4efc4e89ed11
Create Date: 2021-04-15 17:39:10.309266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c7c2181887'
down_revision = '4efc4e89ed11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('ruta', sa.String(length=180), nullable=True),
    sa.Column('dificultad', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('administ_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administ_id'], ['administ.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
