"""empty message

Revision ID: b089bf54d290
Revises: fb5b3ffeb34d
Create Date: 2021-04-17 08:19:25.765199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b089bf54d290'
down_revision = 'fb5b3ffeb34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('gears', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'gears')
    # ### end Alembic commands ###
