"""empty message

Revision ID: c0f49d8264f1
Revises: 67c7c2181887
Create Date: 2021-04-17 10:29:22.514328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f49d8264f1'
down_revision = '67c7c2181887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('descripcion', sa.String(length=10000000), nullable=True))
    op.drop_column('activity', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('activity', 'descripcion')
    # ### end Alembic commands ###
