"""empty message

Revision ID: cf035d5b5c7e
Revises: c0f49d8264f1
Create Date: 2021-04-18 15:09:19.257108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf035d5b5c7e'
down_revision = 'c0f49d8264f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('description', sa.String(length=10000000), nullable=True))
    op.add_column('activity', sa.Column('dificulty', sa.Integer(), nullable=True))
    op.drop_column('activity', 'dificultad')
    op.drop_column('activity', 'ruta')
    op.drop_column('activity', 'descripcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('descripcion', sa.VARCHAR(length=10000000), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('ruta', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('dificultad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('activity', 'dificulty')
    op.drop_column('activity', 'description')
    # ### end Alembic commands ###
