"""empty message

Revision ID: e1fc586a6933
Revises: f353900f09ac
Create Date: 2021-04-18 15:15:31.500717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fc586a6933'
down_revision = 'f353900f09ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('dificulty', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'dificulty')
    # ### end Alembic commands ###
