"""empty message

Revision ID: f353900f09ac
Revises: cf035d5b5c7e
Create Date: 2021-04-18 15:12:58.115928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f353900f09ac'
down_revision = 'cf035d5b5c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('route', sa.String(length=180), nullable=True))
    op.drop_column('activity', 'dificulty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('dificulty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('activity', 'route')
    # ### end Alembic commands ###
