"""empty message

Revision ID: fe1e351af93e
Revises: 03049b898aee
Create Date: 2021-04-19 16:49:08.796313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1e351af93e'
down_revision = '03049b898aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'gears')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('gears', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
